name: Go
on:
  push:
    branches:
      - master
  pull_request: {}
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - uses: actions/checkout@v4

      - name: Get dependencies
        run: go mod download

      - name: Test
        run: go test -v ./...

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
          args: -c .golangci.yml
